# Generated by Django 3.0.5 on 2020-05-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20200513_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chennai_Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(max_length=64)),
                ('Job_Title', models.CharField(max_length=64)),
                ('Experience', models.CharField(max_length=64)),
                ('Location', models.CharField(max_length=64)),
                ('Salary', models.IntegerField()),
                ('Posted_date', models.CharField(max_length=64)),
            ],
        ),
    ]
