# Generated by Django 3.0.5 on 2020-05-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_chennai_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='banglore_jobs',
            name='Qualification',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chennai_jobs',
            name='Qualification',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hyd_jobs',
            name='Qualification',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pune_jobs',
            name='Qualification',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
